import type { Metadata } from "next";
import "@/public/fonts/satoshi/satoshi.css";
import "@/public/fonts/integral/integral.css";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background antialiased font-satoshi">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
